"""Signal: a candidate trade idea generated by a strategy.

A Signal is NOT a decision to trade. It's a strategy saying "this looks
interesting". The decision engine evaluates it against cost and confluence
rules before it becomes an order.
"""

from __future__ import annotations

from datetime import datetime
from decimal import Decimal
from enum import Enum, StrEnum

from pydantic import BaseModel, ConfigDict, Field


class Direction(StrEnum):
    """Trade direction. LONG = bull cert. SHORT = bear cert."""

    LONG = "long"
    SHORT = "short"


class Conviction(int, Enum):
    """How strongly the strategy believes in this signal.

    Maps to position sizing in the decision engine:
    - LOW: usually filtered out unless very cheap to attempt
    - MEDIUM: small position
    - HIGH: normal position
    - VERY_HIGH: max position (still capped by hard limits)
    """

    LOW = 1
    MEDIUM = 2
    HIGH = 3
    VERY_HIGH = 4


class Signal(BaseModel):
    """A candidate trade idea. Not yet a decision to trade.

    Signals are immutable. Strategies produce them; the decision engine
    evaluates them. No mutation in flight.
    """

    model_config = ConfigDict(frozen=True)

    timestamp: datetime
    strategy_name: str
    instrument: str  # Underlying ticker, e.g. "^OMX", "^NDX"
    direction: Direction
    conviction: Conviction
    suggested_entry: Decimal
    suggested_stop: Decimal
    suggested_target: Decimal
    confluence_factors: list[str] = Field(default_factory=list)
    notes: str = ""

    @property
    def reward_to_risk(self) -> Decimal:
        """Reward-to-risk ratio based on suggested levels.

        For LONG: (target - entry) / (entry - stop)
        For SHORT: (entry - target) / (stop - entry)
        """
        if self.direction == Direction.LONG:
            reward = self.suggested_target - self.suggested_entry
            risk = self.suggested_entry - self.suggested_stop
        else:
            reward = self.suggested_entry - self.suggested_target
            risk = self.suggested_stop - self.suggested_entry

        if risk <= 0:
            raise ValueError(
                f"Signal has non-positive risk: entry={self.suggested_entry}, "
                f"stop={self.suggested_stop}, direction={self.direction}"
            )
        return reward / risk
